### ISSUE TITLE
Mysql

### ISSUE THREAD

**Issue by joper112** [hvanderlaan/p2000#25]
Hallo,

Is het mogelijk om de data te exporteren naar een mysql database? en eventueel om het script continue te laten lopen en dat die dan live de meldingen ophaalt?

**Comment by hvanderlaan** [comment]
Hey Joper112,

Op dit moment zit er geen optie in het script om de gegevens weg te schrijven naar een mysql database. Dit is echt niet onmogelijk, als je python-mysql module gebruikt en in p2000lib/p2000.py zou je de class DisplayMessage aanpassen zodat de data niet naar het scherm stuurt maar naar een database.

Om het script continue te laten draaien is het mogelijk om in p2000.py een while true loop te maken met een sleep 60 zodat het script elke 60 seconde de gegevens ophaalt. Dan moet je er alleen op letten dat alleen de nieuwe data in de database komt.

Ik was al wel bezig met een daemon modus zodat het script continue draait, misschien voeg ik dat ook mysql of sqlite3 ondersteuning er in. Als je de p2000 repo forkt of er een clone van maakt kan je altijd de laatste update verkrijgen via GitHub.
