### ISSUE TITLE
How to open the script

### ISSUE THREAD

**Issue by 112bzo** [hvanderlaan/p2000#36]
Hoe kan ik uw script uitvoeren

**Comment by hvanderlaan** [comment]
@112bzo Als je windows gebruikt moet je eerst python voor windows downloaden. Daarna kan je op de command prompt het volgende commando opgeven `python p2000.py`

gebruik je linux dan moet je een terminal openen en kan je het commando `python p2000.py` uitvoeren.

Dit alles behalve het windows gedeelte staat in de README.
